"""Export a fitted head into OpenSCAD, so the printed frame fits the person.

The CAD needs to know the shape of the head it is wrapping. Rather than
re-implement ellipse arc-length in OpenSCAD — which has no while loop and no
root finder, and where a forward reference silently evaluates to undef — this
module writes the geometry out as plain data: the head's semi-axes, the band
paths as polylines, and each electrode mount as a point plus the two rotations
that stand a cylinder up along the surface normal.

The .scad files then only have to sweep and subtract, which is what OpenSCAD
is actually good at.
"""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np

from .head import Head
from .ten_twenty import (
    LATERAL_LEFT,
    MIDLINE,
    MONTAGE_V1,
    PHASE_1,
    Site,
    lateral_loop,
    temple_site,
)

# Points per band. 48 is smooth at head scale without making OpenSCAD crawl
# through several thousand hull() operations.
BAND_STEPS = 48


def write_head_params(head: Head, sites: dict[str, Site], path: str | Path) -> Path:
    """Write the head geometry and band paths as an OpenSCAD include file."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    sagittal = head.sagittal_arc()
    coronal = head.coronal_arc()
    _, loop_len = lateral_loop(head, sites)
    loop = head.circumference_arc(float(sites["Fpz"].xyz_mm[2] + sites["Oz"].xyz_mm[2]) / 2.0)

    # A closed ring plus two arches. Separate front and rear bands would each
    # be cantilevered off a single joint at the midline and would flex; a
    # closed loop braced by two arches is stiff, and is how EEG caps are built.
    bands = {
        # The ring, carrying Fpz, the temples, T7, T8, O1, Oz and O2.
        "lateral": _sample(loop, 0.0, 1.0, closed=True),
        # Over the top, front to back.
        "sagittal": _sample(sagittal, MIDLINE["Fpz"], MIDLINE["Oz"]),
        # Ear to ear over the vertex, carrying C3, Cz and C4.
        "coronal": _sample(coronal, LATERAL_LEFT["T7"], 1.0 - LATERAL_LEFT["T7"]),
        # Two more arches, because F3, F4, P3 and P4 sit on neither the ring
        # nor either existing arch. These are the standard frontal and parietal
        # chains, and both land on the ring at their ends, so they brace it
        # rather than hanging off it.
        "frontal": _surface_path(head, [sites[n].xyz_mm for n in ("F7", "F3", "Fz", "F4", "F8")]),
        "parietal": _surface_path(head, [sites[n].xyz_mm for n in ("P7", "P3", "Pz", "P4", "P8")]),
    }

    lines = [
        "// Generated by nsc_fit — do not edit.",
        f"// Fitted from circumference {head.measurements.circumference_mm:.0f} mm, "
        f"nasion-inion {head.measurements.nasion_inion_mm:.0f} mm, "
        f"ear-to-ear {head.measurements.preauricular_mm:.0f} mm.",
        "",
        f"head_axes = [{head.a_mm:.3f}, {head.b_mm:.3f}, {head.c_mm:.3f}];",
        f"lateral_loop_len = {loop_len:.2f};",
        "",
    ]
    for name, points in bands.items():
        lines.append(f"band_{name} = {_vector_list(points)};")
    lines.append("")

    # Electrode mounts, as one list so adding or dropping a site needs no edit
    # to the CAD: [name, position, rotation, phase_one].
    # The rotation aligns +Z with the outward surface normal, so every socket
    # stands straight out of the skull instead of being eyeballed.
    lines.append("// [name, position, [rot_x, rot_y, rot_z], phase_one]")
    entries = []
    for name in MONTAGE_V1:
        point = sites[name].xyz_mm
        elevation, azimuth = _normal_rotation(head, point)
        flag = 1 if name in PHASE_1 else 0
        entries.append(
            f'["{name}", {_vector(point)}, [0, {elevation:.3f}, {azimuth:.3f}], {flag}]'
        )
    lines.append("mounts = [\n    " + ",\n    ".join(entries) + "\n];")
    lines.append("")

    # The PPG sensor seat on the temple.
    temple = temple_site(head, sites)
    elevation, azimuth = _normal_rotation(head, temple.xyz_mm)
    lines.append(
        f"ppg_mount = [{_vector(temple.xyz_mm)}, [0, {elevation:.3f}, {azimuth:.3f}]];"
    )

    # The pod sits behind and below Oz, on the flat of the occiput.
    pod_point = loop.at_fraction(0.5)
    elevation, azimuth = _normal_rotation(head, pod_point)
    lines.append("")
    lines.append(f"pod_anchor = [{_vector(pod_point)}, [0, {elevation:.3f}, {azimuth:.3f}]];")

    path.write_text("\n".join(lines) + "\n")
    return path


def _sample(arc, start_fraction: float, end_fraction: float, closed: bool = False) -> np.ndarray:
    """Sample a band path evenly along an arc, by arc length not by angle.

    ``closed`` repeats the first point at the end so a swept ring joins up
    instead of leaving a gap the width of one step.
    """
    fractions = np.linspace(start_fraction, end_fraction, BAND_STEPS)
    points = np.array([arc.at_fraction(min(f, 1.0)) for f in fractions])
    if closed:
        points[-1] = points[0]
    return points


def _surface_path(head: Head, control_points: list, steps: int = 14) -> np.ndarray:
    """A smooth path across the head through a list of points on its surface.

    The frontal and parietal chains are not planar ellipses — F3 and P3 are
    defined as lying between two other sites, so the chain through them is a
    curve with no closed form. Interpolating in the plane and projecting
    afterwards would sag the path inside the skull between control points.

    Instead the points are mapped to a unit sphere, where the shortest path
    between two of them is a great-circle arc with an exact formula, and then
    mapped back. Every sampled point lands on the head surface by construction.
    """
    axes = np.array([head.a_mm, head.b_mm, head.c_mm])
    units = [p / axes for p in control_points]
    units = [u / np.linalg.norm(u) for u in units]

    out: list[np.ndarray] = []
    for i in range(len(units) - 1):
        a, b = units[i], units[i + 1]
        omega = math.acos(float(np.clip(np.dot(a, b), -1.0, 1.0)))
        last = i == len(units) - 2
        for t in np.linspace(0.0, 1.0, steps, endpoint=last):
            if omega < 1e-9:
                point = a
            else:
                point = (math.sin((1 - t) * omega) * a + math.sin(t * omega) * b) / math.sin(omega)
            out.append(point * axes)
    return np.array(out)


def _normal_rotation(head: Head, point: np.ndarray) -> tuple[float, float]:
    """Rotations in degrees that align +Z with the outward normal at ``point``.

    The gradient of x²/a² + y²/b² + z²/c² gives the normal directly. OpenSCAD's
    rotate([0, elevation, azimuth]) then maps +Z onto it.
    """
    axes = np.array([head.a_mm, head.b_mm, head.c_mm])
    normal = point / (axes**2)
    normal = normal / np.linalg.norm(normal)
    elevation = math.degrees(math.acos(float(np.clip(normal[2], -1.0, 1.0))))
    azimuth = math.degrees(math.atan2(float(normal[1]), float(normal[0])))
    return elevation, azimuth


def _vector(point) -> str:
    return "[" + ", ".join(f"{v:.3f}" for v in point) + "]"


def _vector_list(points) -> str:
    return "[" + ", ".join(_vector(p) for p in points) + "]"
